# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_Name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Date_Added',
        ),
    ]
